### ISSUE TITLE
Practica_3

### ISSUE THREAD

**Issue by Daisy-GonzalezLita12** [SistemasTecTlaxiaco/actividad-3-practica-architect-Daisy-GonzalezLita12-4#1]
[Practica_03_Ingeniería de software.pdf](https://github.com/user-attachments/files/16858639/Practica_03_Ingenieria.de.software.pdf)

**Comment by evelyn-santiago** [comment]
20 /20 
cumple con todos los criterios de la rubrica

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
